seed: 1
algorithm: mtl
net: dpot2d
dataset: ns2d_fno_1e-3
save_name: mtl_cagrad
save_dir: ./saved_models_comp/dpot_ns2d_1e-3/multi_objective/
load_path: ./saved_models_comp/dpot_ns2d_1e-3/multi_objective/mtl_cagrad/latest_model.pth
# 
resume: false
overwrite: true
use_tensorboard: false
dataset_type: temporal
normalize: false
# FOR DATASET CONFIGURATIONS
img_size: 64, 64
res: 64
n_channels: 1
T_in: 10
T_ar: 20
T_bundle: 1
# FOR OPTIMIZATION CONFIGURATIONS
epochs: 500
num_train_iter: 32000
num_eval_iter: 16
num_log_iter: 8
batch_size: 16
eval_batch_size: 16
# 
optim: adamw
beta1: 0.9
beta2: 0.999
# 
clip_grad: 5.0
warmup_epochs: 50
weight_decay: 1e-6
lr: 0.001
lr_method: cycle
# FOR TRAINING CONFIGURATIONS
train_sampler: RandomSampler
num_workers: 8
world_size: 1
rank: 0
multiprocessing_distributed: false
dist_url: tcp://127.0.0.1:22647
dist_backend: nccl
gpu: None
# DPOT SPECIFIC CONFIGURATIONS
patch_size: 4
width: 512
mlp_ratio: 1
n_blocks: 4
n_layers: 4
modes: 32
out_layer_dim: 32
act: gelu
mixing_type: afno
time_agg: exp_mlp
use_ln: false
# FOR ADDITIONAL TRAINING CONFIGURATIONS
use_proj_grad: true
proj_type: cagrad
noise_scale: 0.0